### PR TITLE
[GH-7] Throw a server connect error more clearly

### LINKED ISSUE #7: Throw a server connect error more clearly
If MM can't connect to the clamav server, the returned error is not very clear.  You'll notice that it's not working because you can't post any attachments at all and the error says "Error while scanning for viruses"

### PR DESCRIPTION
**Pull request by anidok**
**Summary**

Ping ClamAV server before forwarding uploaded files for scannig. Throw and log error with specific message if the server is unreachable.

**Ticket Link**

Fixes https://github.com/mattermost/mattermost-plugin-antivirus/issues/7

**Screenshots**

image

image

### CODE REVIEW

**Comment by anidok** [comment]
I realise that the ci-build is failing. I suspect it's not a code issue but something related to this issue:
https://github.com/mattermost/mattermost-plugin-starter-template/issues/65

To test this, I created a dummy branch from master and added a dummy commit. That build is also failing. Please have a look at below dummy PR build.
https://github.com/mattermost/mattermost-plugin-antivirus/pull/12

**Comment by hanzei** [comment]
Sorry for the inconvenience @anidok. I've submitted #13 to fix the CI.

**Comment by anidok** [comment]
> Sorry for the inconvenience @anidok. I've submitted #13 to fix the CI.

Thanks @hanzei

**Review by aaronrothschild — APPROVED** [review]

File: server/plugin.go [hunk 1]
```diff
@@ -22,6 +22,12 @@ func (p *Plugin) FileWillBeUploaded(c *plugin.Context, info *model.FileInfo, fil
 	config := p.getConfiguration()
 
 	av := clamd.NewClamd("tcp://" + config.ClamavHostPort)
+	err := av.Ping()
```
Comment (crspeller) [inline server/plugin.go]: Could we simplify this and just return the nice error message on line 35? Do we need an extra round trip the the AV server?

**Review by crspeller — CHANGES_REQUESTED** [review]

File: server/plugin.go (hunk 1 above)
Comment (anidok) [reply server/plugin.go]: If we directly return the server unreachable error message in line 35, it will become generic for all error scenarios of av.ScanStream() function. So, even if server is up and running but ScanStream() threw error while reading the stream, it will show as server unreachable only. 

Yes, we should try to avoid the round trip to the AV server. In that case, we would need an extra check inside if condition of line 33, something like 

```
if strings.Contains(err.Error(), "connection refused"){
		// return error message
}
```

Let me know your views.

Comment (crspeller) [reply server/plugin.go]: From a user's point of view. The detail of the message isn't increased by saying the server was unreachable. The administrator, to debug the issue, would still have to look in the logs and contact the admin for assistance.

Comment (anidok) [reply server/plugin.go]: Thanks for your valuable feedback. I have made the changes accordingly so that now we don't do an extra ping and just throw the custom error inside ScanStream() function itself.

Let me know if that's what is expected.

**Review by crspeller — APPROVED** [review]
Great! Thanks for the contribution!

**Comment by anidok** [comment]
> Great! Thanks for the contribution!

Thanks for your patience and time. :)

**Review by cpoile — APPROVED** [review]
Thanks @anidok, and for the responsiveness to the feedback!

**Comment by cpoile** [comment]
@DHaussermann Sorry, I pressed the merge button reflexively before checking if you had approved. Can you add this to your list to test in master?  Apologies.

**Comment by anidok** [comment]
Thanks everyone for your patience. This was my first ever open source contribution. I look forward to contribute more.

**Comment by DHaussermann** [comment]
No worries @cpoile :)Thanks for the heads up. 
I tested this on master and confirmed that I see the message when the server configured is unreachable.
Added a release test to cover this new functionality.
